### ISSUE TITLE
Protect bookmark from reading page colors

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#246]
When run on https://anori.sinja.io/

It reads the global background created by the page:

```css
:root {
   --backround: #fff;
}
```

There is a need to add default colors.
