### ISSUE TITLE
SRFI-210 breaks bookmarklet REPL

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#287]
The [SRFI-210](https://srfi.schemers.org/srfi-210/srfi-210.html)

Defines this CSS:

```css
      span.token
      {
          font-family: serif;
      }
      span.token::before
      {
          content: "〈";
      }
      span.token::after
      {
          content: "〉";
      }
```

Which breaks the REPL.
