### ISSUE TITLE
CodePen demo tooltip issue

### ISSUE THREAD

**Issue by jcubic** [jcubic/lips#435]
There is weird behavior of LIPS REPL on CodePen

https://codepen.io/jcubic/pen/YzqwoJd

It should be the same as Bookmarklet

![Image](https://github.com/user-attachments/assets/9dc13590-5299-47cd-9db8-738b9b7b4cb1)

- [x] Fix the issue
- [x] Check bookmarklet

**Comment by jcubic** [comment]
the problem is this code from jQuery Terminal:

```css
body.full-screen-terminal .terminal {
    height: 100% !important;
}
```
